// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Member struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	OrderNum             int64    `protobuf:"varint,6,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{0}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetOrderNum() int64 {
	if m != nil {
		return m.OrderNum
	}
	return 0
}

func (m *Member) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Member) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GetMemberByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberByIDReq) Reset()         { *m = GetMemberByIDReq{} }
func (m *GetMemberByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetMemberByIDReq) ProtoMessage()    {}
func (*GetMemberByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{1}
}

func (m *GetMemberByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberByIDReq.Unmarshal(m, b)
}
func (m *GetMemberByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberByIDReq.Marshal(b, m, deterministic)
}
func (m *GetMemberByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberByIDReq.Merge(m, src)
}
func (m *GetMemberByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetMemberByIDReq.Size(m)
}
func (m *GetMemberByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberByIDReq proto.InternalMessageInfo

func (m *GetMemberByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MemberResp struct {
	Member               *Member  `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberResp) Reset()         { *m = MemberResp{} }
func (m *MemberResp) String() string { return proto.CompactTextString(m) }
func (*MemberResp) ProtoMessage()    {}
func (*MemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{2}
}

func (m *MemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberResp.Unmarshal(m, b)
}
func (m *MemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberResp.Marshal(b, m, deterministic)
}
func (m *MemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberResp.Merge(m, src)
}
func (m *MemberResp) XXX_Size() int {
	return xxx_messageInfo_MemberResp.Size(m)
}
func (m *MemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_MemberResp proto.InternalMessageInfo

func (m *MemberResp) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type GetMemberByPhoneReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberByPhoneReq) Reset()         { *m = GetMemberByPhoneReq{} }
func (m *GetMemberByPhoneReq) String() string { return proto.CompactTextString(m) }
func (*GetMemberByPhoneReq) ProtoMessage()    {}
func (*GetMemberByPhoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{3}
}

func (m *GetMemberByPhoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberByPhoneReq.Unmarshal(m, b)
}
func (m *GetMemberByPhoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberByPhoneReq.Marshal(b, m, deterministic)
}
func (m *GetMemberByPhoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberByPhoneReq.Merge(m, src)
}
func (m *GetMemberByPhoneReq) XXX_Size() int {
	return xxx_messageInfo_GetMemberByPhoneReq.Size(m)
}
func (m *GetMemberByPhoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberByPhoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberByPhoneReq proto.InternalMessageInfo

func (m *GetMemberByPhoneReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetMemberMaxAgeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberMaxAgeReq) Reset()         { *m = GetMemberMaxAgeReq{} }
func (m *GetMemberMaxAgeReq) String() string { return proto.CompactTextString(m) }
func (*GetMemberMaxAgeReq) ProtoMessage()    {}
func (*GetMemberMaxAgeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{4}
}

func (m *GetMemberMaxAgeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberMaxAgeReq.Unmarshal(m, b)
}
func (m *GetMemberMaxAgeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberMaxAgeReq.Marshal(b, m, deterministic)
}
func (m *GetMemberMaxAgeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberMaxAgeReq.Merge(m, src)
}
func (m *GetMemberMaxAgeReq) XXX_Size() int {
	return xxx_messageInfo_GetMemberMaxAgeReq.Size(m)
}
func (m *GetMemberMaxAgeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberMaxAgeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberMaxAgeReq proto.InternalMessageInfo

type GetMemberMaxAgeResp struct {
	Age                  int64    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberMaxAgeResp) Reset()         { *m = GetMemberMaxAgeResp{} }
func (m *GetMemberMaxAgeResp) String() string { return proto.CompactTextString(m) }
func (*GetMemberMaxAgeResp) ProtoMessage()    {}
func (*GetMemberMaxAgeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{5}
}

func (m *GetMemberMaxAgeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberMaxAgeResp.Unmarshal(m, b)
}
func (m *GetMemberMaxAgeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberMaxAgeResp.Marshal(b, m, deterministic)
}
func (m *GetMemberMaxAgeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberMaxAgeResp.Merge(m, src)
}
func (m *GetMemberMaxAgeResp) XXX_Size() int {
	return xxx_messageInfo_GetMemberMaxAgeResp.Size(m)
}
func (m *GetMemberMaxAgeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberMaxAgeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberMaxAgeResp proto.InternalMessageInfo

func (m *GetMemberMaxAgeResp) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type QueryMemberByNameReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMemberByNameReq) Reset()         { *m = QueryMemberByNameReq{} }
func (m *QueryMemberByNameReq) String() string { return proto.CompactTextString(m) }
func (*QueryMemberByNameReq) ProtoMessage()    {}
func (*QueryMemberByNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{6}
}

func (m *QueryMemberByNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMemberByNameReq.Unmarshal(m, b)
}
func (m *QueryMemberByNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMemberByNameReq.Marshal(b, m, deterministic)
}
func (m *QueryMemberByNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMemberByNameReq.Merge(m, src)
}
func (m *QueryMemberByNameReq) XXX_Size() int {
	return xxx_messageInfo_QueryMemberByNameReq.Size(m)
}
func (m *QueryMemberByNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMemberByNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMemberByNameReq proto.InternalMessageInfo

func (m *QueryMemberByNameReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryMemberByNameResp struct {
	List                 []*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryMemberByNameResp) Reset()         { *m = QueryMemberByNameResp{} }
func (m *QueryMemberByNameResp) String() string { return proto.CompactTextString(m) }
func (*QueryMemberByNameResp) ProtoMessage()    {}
func (*QueryMemberByNameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{7}
}

func (m *QueryMemberByNameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMemberByNameResp.Unmarshal(m, b)
}
func (m *QueryMemberByNameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMemberByNameResp.Marshal(b, m, deterministic)
}
func (m *QueryMemberByNameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMemberByNameResp.Merge(m, src)
}
func (m *QueryMemberByNameResp) XXX_Size() int {
	return xxx_messageInfo_QueryMemberByNameResp.Size(m)
}
func (m *QueryMemberByNameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMemberByNameResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMemberByNameResp proto.InternalMessageInfo

func (m *QueryMemberByNameResp) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

type QueryMemberByIDsReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMemberByIDsReq) Reset()         { *m = QueryMemberByIDsReq{} }
func (m *QueryMemberByIDsReq) String() string { return proto.CompactTextString(m) }
func (*QueryMemberByIDsReq) ProtoMessage()    {}
func (*QueryMemberByIDsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{8}
}

func (m *QueryMemberByIDsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMemberByIDsReq.Unmarshal(m, b)
}
func (m *QueryMemberByIDsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMemberByIDsReq.Marshal(b, m, deterministic)
}
func (m *QueryMemberByIDsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMemberByIDsReq.Merge(m, src)
}
func (m *QueryMemberByIDsReq) XXX_Size() int {
	return xxx_messageInfo_QueryMemberByIDsReq.Size(m)
}
func (m *QueryMemberByIDsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMemberByIDsReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMemberByIDsReq proto.InternalMessageInfo

func (m *QueryMemberByIDsReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type QueryMemberByIDsResp struct {
	List                 map[int64]*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryMemberByIDsResp) Reset()         { *m = QueryMemberByIDsResp{} }
func (m *QueryMemberByIDsResp) String() string { return proto.CompactTextString(m) }
func (*QueryMemberByIDsResp) ProtoMessage()    {}
func (*QueryMemberByIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{9}
}

func (m *QueryMemberByIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMemberByIDsResp.Unmarshal(m, b)
}
func (m *QueryMemberByIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMemberByIDsResp.Marshal(b, m, deterministic)
}
func (m *QueryMemberByIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMemberByIDsResp.Merge(m, src)
}
func (m *QueryMemberByIDsResp) XXX_Size() int {
	return xxx_messageInfo_QueryMemberByIDsResp.Size(m)
}
func (m *QueryMemberByIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMemberByIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMemberByIDsResp proto.InternalMessageInfo

func (m *QueryMemberByIDsResp) GetList() map[int64]*Member {
	if m != nil {
		return m.List
	}
	return nil
}

type AddMemberReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberReq) Reset()         { *m = AddMemberReq{} }
func (m *AddMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddMemberReq) ProtoMessage()    {}
func (*AddMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{10}
}

func (m *AddMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberReq.Unmarshal(m, b)
}
func (m *AddMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberReq.Marshal(b, m, deterministic)
}
func (m *AddMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberReq.Merge(m, src)
}
func (m *AddMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddMemberReq.Size(m)
}
func (m *AddMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberReq proto.InternalMessageInfo

func (m *AddMemberReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddMemberReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddMemberReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *AddMemberReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type BatchAddMemberReq struct {
	AddMemberReq         []*AddMemberReq `protobuf:"bytes,1,rep,name=addMemberReq,proto3" json:"addMemberReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BatchAddMemberReq) Reset()         { *m = BatchAddMemberReq{} }
func (m *BatchAddMemberReq) String() string { return proto.CompactTextString(m) }
func (*BatchAddMemberReq) ProtoMessage()    {}
func (*BatchAddMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{11}
}

func (m *BatchAddMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchAddMemberReq.Unmarshal(m, b)
}
func (m *BatchAddMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchAddMemberReq.Marshal(b, m, deterministic)
}
func (m *BatchAddMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchAddMemberReq.Merge(m, src)
}
func (m *BatchAddMemberReq) XXX_Size() int {
	return xxx_messageInfo_BatchAddMemberReq.Size(m)
}
func (m *BatchAddMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchAddMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_BatchAddMemberReq proto.InternalMessageInfo

func (m *BatchAddMemberReq) GetAddMemberReq() []*AddMemberReq {
	if m != nil {
		return m.AddMemberReq
	}
	return nil
}

type BatchAddMemberResp struct {
	AffectRow            int64    `protobuf:"varint,1,opt,name=affectRow,proto3" json:"affectRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchAddMemberResp) Reset()         { *m = BatchAddMemberResp{} }
func (m *BatchAddMemberResp) String() string { return proto.CompactTextString(m) }
func (*BatchAddMemberResp) ProtoMessage()    {}
func (*BatchAddMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{12}
}

func (m *BatchAddMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchAddMemberResp.Unmarshal(m, b)
}
func (m *BatchAddMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchAddMemberResp.Marshal(b, m, deterministic)
}
func (m *BatchAddMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchAddMemberResp.Merge(m, src)
}
func (m *BatchAddMemberResp) XXX_Size() int {
	return xxx_messageInfo_BatchAddMemberResp.Size(m)
}
func (m *BatchAddMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchAddMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_BatchAddMemberResp proto.InternalMessageInfo

func (m *BatchAddMemberResp) GetAffectRow() int64 {
	if m != nil {
		return m.AffectRow
	}
	return 0
}

type InitMemberReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMemberReq) Reset()         { *m = InitMemberReq{} }
func (m *InitMemberReq) String() string { return proto.CompactTextString(m) }
func (*InitMemberReq) ProtoMessage()    {}
func (*InitMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{13}
}

func (m *InitMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMemberReq.Unmarshal(m, b)
}
func (m *InitMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMemberReq.Marshal(b, m, deterministic)
}
func (m *InitMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMemberReq.Merge(m, src)
}
func (m *InitMemberReq) XXX_Size() int {
	return xxx_messageInfo_InitMemberReq.Size(m)
}
func (m *InitMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitMemberReq proto.InternalMessageInfo

func (m *InitMemberReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *InitMemberReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitMemberReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *InitMemberReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type IDResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDResp) Reset()         { *m = IDResp{} }
func (m *IDResp) String() string { return proto.CompactTextString(m) }
func (*IDResp) ProtoMessage()    {}
func (*IDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{14}
}

func (m *IDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDResp.Unmarshal(m, b)
}
func (m *IDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDResp.Marshal(b, m, deterministic)
}
func (m *IDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDResp.Merge(m, src)
}
func (m *IDResp) XXX_Size() int {
	return xxx_messageInfo_IDResp.Size(m)
}
func (m *IDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IDResp.DiscardUnknown(m)
}

var xxx_messageInfo_IDResp proto.InternalMessageInfo

func (m *IDResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteMemberReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMemberReq) Reset()         { *m = DeleteMemberReq{} }
func (m *DeleteMemberReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberReq) ProtoMessage()    {}
func (*DeleteMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{15}
}

func (m *DeleteMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMemberReq.Unmarshal(m, b)
}
func (m *DeleteMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMemberReq.Marshal(b, m, deterministic)
}
func (m *DeleteMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMemberReq.Merge(m, src)
}
func (m *DeleteMemberReq) XXX_Size() int {
	return xxx_messageInfo_DeleteMemberReq.Size(m)
}
func (m *DeleteMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMemberReq proto.InternalMessageInfo

func (m *DeleteMemberReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EmptyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResp) Reset()         { *m = EmptyResp{} }
func (m *EmptyResp) String() string { return proto.CompactTextString(m) }
func (*EmptyResp) ProtoMessage()    {}
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{16}
}

func (m *EmptyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResp.Unmarshal(m, b)
}
func (m *EmptyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResp.Marshal(b, m, deterministic)
}
func (m *EmptyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResp.Merge(m, src)
}
func (m *EmptyResp) XXX_Size() int {
	return xxx_messageInfo_EmptyResp.Size(m)
}
func (m *EmptyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResp proto.InternalMessageInfo

type SetMemberReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMemberReq) Reset()         { *m = SetMemberReq{} }
func (m *SetMemberReq) String() string { return proto.CompactTextString(m) }
func (*SetMemberReq) ProtoMessage()    {}
func (*SetMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{17}
}

func (m *SetMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMemberReq.Unmarshal(m, b)
}
func (m *SetMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMemberReq.Marshal(b, m, deterministic)
}
func (m *SetMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMemberReq.Merge(m, src)
}
func (m *SetMemberReq) XXX_Size() int {
	return xxx_messageInfo_SetMemberReq.Size(m)
}
func (m *SetMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetMemberReq proto.InternalMessageInfo

func (m *SetMemberReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetMemberReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SetMemberReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetMemberReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SetMemberReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateMemberReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMemberReq) Reset()         { *m = UpdateMemberReq{} }
func (m *UpdateMemberReq) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberReq) ProtoMessage()    {}
func (*UpdateMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{18}
}

func (m *UpdateMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMemberReq.Unmarshal(m, b)
}
func (m *UpdateMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMemberReq.Marshal(b, m, deterministic)
}
func (m *UpdateMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberReq.Merge(m, src)
}
func (m *UpdateMemberReq) XXX_Size() int {
	return xxx_messageInfo_UpdateMemberReq.Size(m)
}
func (m *UpdateMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberReq proto.InternalMessageInfo

func (m *UpdateMemberReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateMemberReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateMemberReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateMemberReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UpdateMemberReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateSomeMemberReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSomeMemberReq) Reset()         { *m = UpdateSomeMemberReq{} }
func (m *UpdateSomeMemberReq) String() string { return proto.CompactTextString(m) }
func (*UpdateSomeMemberReq) ProtoMessage()    {}
func (*UpdateSomeMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{19}
}

func (m *UpdateSomeMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSomeMemberReq.Unmarshal(m, b)
}
func (m *UpdateSomeMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSomeMemberReq.Marshal(b, m, deterministic)
}
func (m *UpdateSomeMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSomeMemberReq.Merge(m, src)
}
func (m *UpdateSomeMemberReq) XXX_Size() int {
	return xxx_messageInfo_UpdateSomeMemberReq.Size(m)
}
func (m *UpdateSomeMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSomeMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSomeMemberReq proto.InternalMessageInfo

func (m *UpdateSomeMemberReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateSomeMemberReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateSomeMemberReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateSomeMemberReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UpdateSomeMemberReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SortMember struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNum             int64    `protobuf:"varint,2,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortMember) Reset()         { *m = SortMember{} }
func (m *SortMember) String() string { return proto.CompactTextString(m) }
func (*SortMember) ProtoMessage()    {}
func (*SortMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{20}
}

func (m *SortMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortMember.Unmarshal(m, b)
}
func (m *SortMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortMember.Marshal(b, m, deterministic)
}
func (m *SortMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortMember.Merge(m, src)
}
func (m *SortMember) XXX_Size() int {
	return xxx_messageInfo_SortMember.Size(m)
}
func (m *SortMember) XXX_DiscardUnknown() {
	xxx_messageInfo_SortMember.DiscardUnknown(m)
}

var xxx_messageInfo_SortMember proto.InternalMessageInfo

func (m *SortMember) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SortMember) GetOrderNum() int64 {
	if m != nil {
		return m.OrderNum
	}
	return 0
}

type SortMemberReq struct {
	SortMember           []*SortMember `protobuf:"bytes,1,rep,name=sortMember,proto3" json:"sortMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SortMemberReq) Reset()         { *m = SortMemberReq{} }
func (m *SortMemberReq) String() string { return proto.CompactTextString(m) }
func (*SortMemberReq) ProtoMessage()    {}
func (*SortMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{21}
}

func (m *SortMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortMemberReq.Unmarshal(m, b)
}
func (m *SortMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortMemberReq.Marshal(b, m, deterministic)
}
func (m *SortMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortMemberReq.Merge(m, src)
}
func (m *SortMemberReq) XXX_Size() int {
	return xxx_messageInfo_SortMemberReq.Size(m)
}
func (m *SortMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SortMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_SortMemberReq proto.InternalMessageInfo

func (m *SortMemberReq) GetSortMember() []*SortMember {
	if m != nil {
		return m.SortMember
	}
	return nil
}

type AddFavoriteReq struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFavoriteReq) Reset()         { *m = AddFavoriteReq{} }
func (m *AddFavoriteReq) String() string { return proto.CompactTextString(m) }
func (*AddFavoriteReq) ProtoMessage()    {}
func (*AddFavoriteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{22}
}

func (m *AddFavoriteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFavoriteReq.Unmarshal(m, b)
}
func (m *AddFavoriteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFavoriteReq.Marshal(b, m, deterministic)
}
func (m *AddFavoriteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFavoriteReq.Merge(m, src)
}
func (m *AddFavoriteReq) XXX_Size() int {
	return xxx_messageInfo_AddFavoriteReq.Size(m)
}
func (m *AddFavoriteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFavoriteReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFavoriteReq proto.InternalMessageInfo

func (m *AddFavoriteReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *AddFavoriteReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Member)(nil), "api.Member")
	proto.RegisterType((*GetMemberByIDReq)(nil), "api.GetMemberByIDReq")
	proto.RegisterType((*MemberResp)(nil), "api.MemberResp")
	proto.RegisterType((*GetMemberByPhoneReq)(nil), "api.GetMemberByPhoneReq")
	proto.RegisterType((*GetMemberMaxAgeReq)(nil), "api.GetMemberMaxAgeReq")
	proto.RegisterType((*GetMemberMaxAgeResp)(nil), "api.GetMemberMaxAgeResp")
	proto.RegisterType((*QueryMemberByNameReq)(nil), "api.QueryMemberByNameReq")
	proto.RegisterType((*QueryMemberByNameResp)(nil), "api.QueryMemberByNameResp")
	proto.RegisterType((*QueryMemberByIDsReq)(nil), "api.QueryMemberByIDsReq")
	proto.RegisterType((*QueryMemberByIDsResp)(nil), "api.QueryMemberByIDsResp")
	proto.RegisterMapType((map[int64]*Member)(nil), "api.QueryMemberByIDsResp.ListEntry")
	proto.RegisterType((*AddMemberReq)(nil), "api.AddMemberReq")
	proto.RegisterType((*BatchAddMemberReq)(nil), "api.BatchAddMemberReq")
	proto.RegisterType((*BatchAddMemberResp)(nil), "api.BatchAddMemberResp")
	proto.RegisterType((*InitMemberReq)(nil), "api.InitMemberReq")
	proto.RegisterType((*IDResp)(nil), "api.IDResp")
	proto.RegisterType((*DeleteMemberReq)(nil), "api.DeleteMemberReq")
	proto.RegisterType((*EmptyResp)(nil), "api.EmptyResp")
	proto.RegisterType((*SetMemberReq)(nil), "api.SetMemberReq")
	proto.RegisterType((*UpdateMemberReq)(nil), "api.UpdateMemberReq")
	proto.RegisterType((*UpdateSomeMemberReq)(nil), "api.UpdateSomeMemberReq")
	proto.RegisterType((*SortMember)(nil), "api.SortMember")
	proto.RegisterType((*SortMemberReq)(nil), "api.SortMemberReq")
	proto.RegisterType((*AddFavoriteReq)(nil), "api.AddFavoriteReq")
}

func init() { proto.RegisterFile("member.proto", fileDescriptor_9b9836b7e13de206) }

var fileDescriptor_9b9836b7e13de206 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x96, 0x6d, 0x4f, 0xdb, 0x48,
	0x10, 0xc7, 0xe5, 0x38, 0x04, 0x3c, 0x09, 0x49, 0x18, 0xc2, 0x61, 0xac, 0x3b, 0x1d, 0x2c, 0x2f,
	0x0e, 0x1d, 0x52, 0xe0, 0x72, 0x77, 0x05, 0x55, 0xad, 0xd4, 0xd0, 0x50, 0x04, 0x2a, 0x88, 0x86,
	0xf6, 0x75, 0x65, 0xf0, 0x02, 0x16, 0x38, 0x76, 0xbd, 0x1b, 0x68, 0xd4, 0xcf, 0xd1, 0xef, 0xd4,
	0xaf, 0xd3, 0x6f, 0x50, 0x79, 0xfd, 0x90, 0xf5, 0xda, 0x79, 0x09, 0xef, 0xbc, 0x33, 0xff, 0xd9,
	0xd9, 0x9d, 0x9d, 0xf9, 0xc9, 0xd0, 0xf0, 0xa8, 0x77, 0x49, 0xc3, 0x6e, 0x10, 0xfa, 0xdc, 0x47,
	0xdd, 0x0e, 0x5c, 0xf2, 0x43, 0x83, 0xda, 0xa9, 0xb0, 0x62, 0x13, 0x2a, 0xae, 0x63, 0x6a, 0xeb,
	0xda, 0x96, 0x3e, 0xac, 0xb8, 0x0e, 0x76, 0x60, 0x2e, 0xb8, 0xf5, 0x47, 0xd4, 0xac, 0xac, 0x6b,
	0x5b, 0xc6, 0x30, 0x5e, 0x20, 0x42, 0x75, 0x64, 0x7b, 0xd4, 0xd4, 0x85, 0x51, 0x7c, 0x63, 0x1b,
	0x74, 0xfb, 0x86, 0x9a, 0x55, 0x11, 0x1a, 0x7d, 0xa2, 0x09, 0xf3, 0xb6, 0xe3, 0x84, 0x94, 0x31,
	0x73, 0x4e, 0x08, 0xd3, 0x25, 0x5a, 0xb0, 0xe0, 0x87, 0x0e, 0x0d, 0xcf, 0xc6, 0x9e, 0x59, 0x13,
	0x01, 0xd9, 0x1a, 0xff, 0x00, 0xb8, 0x0a, 0xa9, 0xcd, 0xa9, 0xf3, 0xd9, 0xe6, 0xe6, 0xbc, 0xf0,
	0x1a, 0x89, 0xa5, 0xcf, 0x23, 0xf7, 0x38, 0x70, 0x52, 0xf7, 0x42, 0xec, 0x4e, 0x2c, 0x7d, 0x4e,
	0x08, 0xb4, 0x8f, 0x28, 0x8f, 0x2f, 0x73, 0x30, 0x39, 0x1e, 0x0c, 0xe9, 0x17, 0xf5, 0x4e, 0xe4,
	0x1f, 0x80, 0x58, 0x30, 0xa4, 0x2c, 0xc0, 0x4d, 0xa8, 0xc5, 0x15, 0x11, 0x8a, 0x7a, 0xaf, 0xde,
	0xb5, 0x03, 0xb7, 0x9b, 0x08, 0x12, 0x17, 0xd9, 0x86, 0x65, 0x69, 0xdb, 0xf3, 0xa8, 0x08, 0xd1,
	0xce, 0x59, 0x75, 0x34, 0xa9, 0x3a, 0xa4, 0x03, 0x98, 0x89, 0x4f, 0xed, 0xaf, 0xfd, 0x9b, 0x48,
	0x4b, 0xfe, 0x92, 0xb6, 0x48, 0xad, 0x2c, 0x48, 0xcb, 0xa6, 0x65, 0x65, 0x23, 0x7f, 0x43, 0xe7,
	0xc3, 0x98, 0x86, 0x93, 0x34, 0xdb, 0x99, 0xed, 0x89, 0x64, 0x69, 0xd1, 0xb5, 0x69, 0xd1, 0xc9,
	0x3e, 0xac, 0x94, 0x68, 0x59, 0x80, 0x7f, 0x42, 0xf5, 0xde, 0x65, 0xdc, 0xd4, 0xd6, 0x75, 0xf5,
	0x4e, 0xc2, 0x11, 0x1d, 0x27, 0x17, 0x79, 0x3c, 0x60, 0x51, 0x92, 0x36, 0xe8, 0xae, 0xc3, 0x44,
	0x98, 0x3e, 0x8c, 0x3e, 0xc9, 0x77, 0x4d, 0x39, 0x8f, 0x50, 0xb2, 0x00, 0xf7, 0x72, 0x29, 0x36,
	0x45, 0x8a, 0x32, 0x61, 0xf7, 0xbd, 0xcb, 0xf8, 0xe1, 0x88, 0x87, 0x93, 0x38, 0xb5, 0x35, 0x00,
	0x23, 0x33, 0x45, 0x09, 0xef, 0xe8, 0x24, 0xbd, 0xff, 0x1d, 0x9d, 0xe0, 0x06, 0xcc, 0x3d, 0xd8,
	0xf7, 0xe3, 0xb8, 0xe5, 0x94, 0xb3, 0xc7, 0x9e, 0x97, 0x95, 0x7d, 0x8d, 0x38, 0xd0, 0xe8, 0x3b,
	0x4e, 0xfa, 0x90, 0x33, 0xde, 0x22, 0x2b, 0x5a, 0xa5, 0xd8, 0xa9, 0x7a, 0x69, 0xa7, 0x56, 0x73,
	0x9d, 0x4a, 0x4e, 0x60, 0xe9, 0xc0, 0xe6, 0x57, 0xb7, 0xb9, 0x54, 0xff, 0x43, 0xc3, 0x96, 0xd6,
	0x49, 0x05, 0x96, 0xc4, 0x41, 0x65, 0xe1, 0x30, 0x27, 0x23, 0x3d, 0x40, 0x75, 0x2f, 0x16, 0xe0,
	0xef, 0x60, 0xd8, 0xd7, 0xd7, 0xf4, 0x8a, 0x0f, 0xfd, 0xc7, 0xa4, 0x0c, 0x53, 0x03, 0xa1, 0xb0,
	0x78, 0x3c, 0x72, 0xf9, 0x53, 0x5f, 0xd3, 0x84, 0x5a, 0x34, 0x2b, 0x2c, 0x28, 0x0c, 0xcb, 0x06,
	0xb4, 0x06, 0xf4, 0x9e, 0x72, 0x3a, 0x3d, 0x82, 0x2a, 0xa9, 0x83, 0x71, 0xe8, 0x05, 0x7c, 0x12,
	0xc5, 0x13, 0x0e, 0x8d, 0x0b, 0xca, 0x67, 0x8a, 0x9f, 0x06, 0x28, 0xe4, 0x11, 0x5a, 0x9f, 0x04,
	0x03, 0x9e, 0x3b, 0xf1, 0x37, 0x58, 0x8e, 0x13, 0x5f, 0xf8, 0xde, 0xb3, 0x27, 0xdf, 0x07, 0xb8,
	0xf0, 0x43, 0x3e, 0x03, 0xdd, 0x32, 0x64, 0x2b, 0x79, 0xc8, 0x92, 0x37, 0xb0, 0x38, 0x8d, 0x8c,
	0x0e, 0xbc, 0x03, 0xc0, 0x32, 0x43, 0xd2, 0xd0, 0x2d, 0xd1, 0xd0, 0x92, 0x4e, 0x92, 0x90, 0x17,
	0xd0, 0xec, 0x3b, 0xce, 0x3b, 0xfb, 0xc1, 0x0f, 0x5d, 0x4e, 0x13, 0x74, 0x78, 0xd9, 0x01, 0xa2,
	0xcf, 0xb2, 0xae, 0xec, 0xfd, 0xac, 0x81, 0x91, 0x6c, 0x77, 0xfe, 0x16, 0xf7, 0x60, 0x31, 0x87,
	0x6b, 0x5c, 0x11, 0x39, 0x55, 0x84, 0x5b, 0x2d, 0x19, 0x02, 0x51, 0x9b, 0xbe, 0xce, 0x71, 0x5e,
	0x00, 0x19, 0x4d, 0x35, 0x36, 0xe5, 0x74, 0x31, 0x7c, 0x00, 0x2d, 0x05, 0xc6, 0xb8, 0x9a, 0x8f,
	0xce, 0xc0, 0x6d, 0x99, 0xe5, 0x0e, 0x16, 0xe0, 0x09, 0x2c, 0x15, 0xe8, 0x8b, 0x6b, 0x45, 0x10,
	0x26, 0x04, 0xb7, 0xac, 0x59, 0x2e, 0x16, 0xe0, 0x11, 0xb4, 0x55, 0x78, 0x26, 0x17, 0x2a, 0xc1,
	0xb4, 0xb5, 0x36, 0x93, 0xb6, 0xb8, 0x0d, 0x46, 0x06, 0x18, 0x2c, 0x32, 0xc9, 0x8a, 0x79, 0x9a,
	0x4c, 0x7b, 0x1f, 0x9a, 0x79, 0x24, 0xe1, 0x6f, 0xc2, 0x5d, 0x60, 0x9e, 0xb5, 0x5a, 0x6a, 0x67,
	0x01, 0xee, 0x02, 0x4c, 0x09, 0x85, 0x18, 0xef, 0x2e, 0x23, 0xcb, 0x6a, 0x0a, 0x5b, 0x86, 0x08,
	0xfc, 0x0f, 0x1a, 0x32, 0x52, 0xb0, 0x23, 0xfc, 0x0a, 0x65, 0x0a, 0x51, 0x5d, 0x30, 0x32, 0xb0,
	0x24, 0xf7, 0x92, 0x41, 0x53, 0x96, 0x45, 0x46, 0x42, 0x92, 0x45, 0xa1, 0x44, 0x21, 0xea, 0x15,
	0xb4, 0xd5, 0x79, 0x4e, 0x9e, 0xa1, 0x64, 0xcc, 0x0b, 0xd1, 0xbb, 0xb9, 0x81, 0x44, 0x75, 0x7e,
	0x4a, 0x22, 0x7a, 0x60, 0x1c, 0x86, 0xa1, 0x1f, 0x7e, 0xa4, 0x8c, 0xcf, 0x6a, 0x7e, 0x35, 0x66,
	0x07, 0xea, 0xd2, 0xe8, 0xe1, 0x72, 0xfa, 0xc6, 0xd2, 0x30, 0xe6, 0x5e, 0xf9, 0xb2, 0x26, 0xfe,
	0xf5, 0xfe, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x33, 0xc4, 0x44, 0xff, 0xfb, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberRPCClient is the client API for MemberRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberRPCClient interface {
	// member
	GetMemberByID(ctx context.Context, in *GetMemberByIDReq, opts ...grpc.CallOption) (*MemberResp, error)
	GetMemberByPhone(ctx context.Context, in *GetMemberByPhoneReq, opts ...grpc.CallOption) (*MemberResp, error)
	GetMemberMaxAge(ctx context.Context, in *GetMemberMaxAgeReq, opts ...grpc.CallOption) (*GetMemberMaxAgeResp, error)
	QueryMemberByName(ctx context.Context, in *QueryMemberByNameReq, opts ...grpc.CallOption) (*QueryMemberByNameResp, error)
	QueryMemberByIDs(ctx context.Context, in *QueryMemberByIDsReq, opts ...grpc.CallOption) (*QueryMemberByIDsResp, error)
	AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*IDResp, error)
	BatchAddMember(ctx context.Context, in *BatchAddMemberReq, opts ...grpc.CallOption) (*BatchAddMemberResp, error)
	InitMember(ctx context.Context, in *InitMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	DeleteMember(ctx context.Context, in *DeleteMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	SetMember(ctx context.Context, in *SetMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	UpdateMember(ctx context.Context, in *UpdateMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	UpdateSomeMember(ctx context.Context, in *UpdateSomeMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	SortMember(ctx context.Context, in *SortMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// test
	ErrorTest(ctx context.Context, in *GetMemberByIDReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// favorite
	AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*IDResp, error)
}

type memberRPCClient struct {
	cc *grpc.ClientConn
}

func NewMemberRPCClient(cc *grpc.ClientConn) MemberRPCClient {
	return &memberRPCClient{cc}
}

func (c *memberRPCClient) GetMemberByID(ctx context.Context, in *GetMemberByIDReq, opts ...grpc.CallOption) (*MemberResp, error) {
	out := new(MemberResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/GetMemberByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) GetMemberByPhone(ctx context.Context, in *GetMemberByPhoneReq, opts ...grpc.CallOption) (*MemberResp, error) {
	out := new(MemberResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/GetMemberByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) GetMemberMaxAge(ctx context.Context, in *GetMemberMaxAgeReq, opts ...grpc.CallOption) (*GetMemberMaxAgeResp, error) {
	out := new(GetMemberMaxAgeResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/GetMemberMaxAge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) QueryMemberByName(ctx context.Context, in *QueryMemberByNameReq, opts ...grpc.CallOption) (*QueryMemberByNameResp, error) {
	out := new(QueryMemberByNameResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/QueryMemberByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) QueryMemberByIDs(ctx context.Context, in *QueryMemberByIDsReq, opts ...grpc.CallOption) (*QueryMemberByIDsResp, error) {
	out := new(QueryMemberByIDsResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/QueryMemberByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*IDResp, error) {
	out := new(IDResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) BatchAddMember(ctx context.Context, in *BatchAddMemberReq, opts ...grpc.CallOption) (*BatchAddMemberResp, error) {
	out := new(BatchAddMemberResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/BatchAddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) InitMember(ctx context.Context, in *InitMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/InitMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) DeleteMember(ctx context.Context, in *DeleteMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/DeleteMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) SetMember(ctx context.Context, in *SetMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/SetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) UpdateMember(ctx context.Context, in *UpdateMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/UpdateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) UpdateSomeMember(ctx context.Context, in *UpdateSomeMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/UpdateSomeMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) SortMember(ctx context.Context, in *SortMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/SortMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) ErrorTest(ctx context.Context, in *GetMemberByIDReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/ErrorTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberRPCClient) AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*IDResp, error) {
	out := new(IDResp)
	err := c.cc.Invoke(ctx, "/api.MemberRPC/AddFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberRPCServer is the server API for MemberRPC service.
type MemberRPCServer interface {
	// member
	GetMemberByID(context.Context, *GetMemberByIDReq) (*MemberResp, error)
	GetMemberByPhone(context.Context, *GetMemberByPhoneReq) (*MemberResp, error)
	GetMemberMaxAge(context.Context, *GetMemberMaxAgeReq) (*GetMemberMaxAgeResp, error)
	QueryMemberByName(context.Context, *QueryMemberByNameReq) (*QueryMemberByNameResp, error)
	QueryMemberByIDs(context.Context, *QueryMemberByIDsReq) (*QueryMemberByIDsResp, error)
	AddMember(context.Context, *AddMemberReq) (*IDResp, error)
	BatchAddMember(context.Context, *BatchAddMemberReq) (*BatchAddMemberResp, error)
	InitMember(context.Context, *InitMemberReq) (*EmptyResp, error)
	DeleteMember(context.Context, *DeleteMemberReq) (*EmptyResp, error)
	SetMember(context.Context, *SetMemberReq) (*EmptyResp, error)
	UpdateMember(context.Context, *UpdateMemberReq) (*EmptyResp, error)
	UpdateSomeMember(context.Context, *UpdateSomeMemberReq) (*EmptyResp, error)
	SortMember(context.Context, *SortMemberReq) (*EmptyResp, error)
	// test
	ErrorTest(context.Context, *GetMemberByIDReq) (*EmptyResp, error)
	// favorite
	AddFavorite(context.Context, *AddFavoriteReq) (*IDResp, error)
}

// UnimplementedMemberRPCServer can be embedded to have forward compatible implementations.
type UnimplementedMemberRPCServer struct {
}

func (*UnimplementedMemberRPCServer) GetMemberByID(ctx context.Context, req *GetMemberByIDReq) (*MemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberByID not implemented")
}
func (*UnimplementedMemberRPCServer) GetMemberByPhone(ctx context.Context, req *GetMemberByPhoneReq) (*MemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberByPhone not implemented")
}
func (*UnimplementedMemberRPCServer) GetMemberMaxAge(ctx context.Context, req *GetMemberMaxAgeReq) (*GetMemberMaxAgeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberMaxAge not implemented")
}
func (*UnimplementedMemberRPCServer) QueryMemberByName(ctx context.Context, req *QueryMemberByNameReq) (*QueryMemberByNameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMemberByName not implemented")
}
func (*UnimplementedMemberRPCServer) QueryMemberByIDs(ctx context.Context, req *QueryMemberByIDsReq) (*QueryMemberByIDsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMemberByIDs not implemented")
}
func (*UnimplementedMemberRPCServer) AddMember(ctx context.Context, req *AddMemberReq) (*IDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedMemberRPCServer) BatchAddMember(ctx context.Context, req *BatchAddMemberReq) (*BatchAddMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchAddMember not implemented")
}
func (*UnimplementedMemberRPCServer) InitMember(ctx context.Context, req *InitMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMember not implemented")
}
func (*UnimplementedMemberRPCServer) DeleteMember(ctx context.Context, req *DeleteMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}
func (*UnimplementedMemberRPCServer) SetMember(ctx context.Context, req *SetMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMember not implemented")
}
func (*UnimplementedMemberRPCServer) UpdateMember(ctx context.Context, req *UpdateMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMember not implemented")
}
func (*UnimplementedMemberRPCServer) UpdateSomeMember(ctx context.Context, req *UpdateSomeMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSomeMember not implemented")
}
func (*UnimplementedMemberRPCServer) SortMember(ctx context.Context, req *SortMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortMember not implemented")
}
func (*UnimplementedMemberRPCServer) ErrorTest(ctx context.Context, req *GetMemberByIDReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrorTest not implemented")
}
func (*UnimplementedMemberRPCServer) AddFavorite(ctx context.Context, req *AddFavoriteReq) (*IDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFavorite not implemented")
}

func RegisterMemberRPCServer(s *grpc.Server, srv MemberRPCServer) {
	s.RegisterService(&_MemberRPC_serviceDesc, srv)
}

func _MemberRPC_GetMemberByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).GetMemberByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/GetMemberByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).GetMemberByID(ctx, req.(*GetMemberByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_GetMemberByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberByPhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).GetMemberByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/GetMemberByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).GetMemberByPhone(ctx, req.(*GetMemberByPhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_GetMemberMaxAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberMaxAgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).GetMemberMaxAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/GetMemberMaxAge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).GetMemberMaxAge(ctx, req.(*GetMemberMaxAgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_QueryMemberByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemberByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).QueryMemberByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/QueryMemberByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).QueryMemberByName(ctx, req.(*QueryMemberByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_QueryMemberByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemberByIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).QueryMemberByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/QueryMemberByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).QueryMemberByIDs(ctx, req.(*QueryMemberByIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).AddMember(ctx, req.(*AddMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_BatchAddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAddMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).BatchAddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/BatchAddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).BatchAddMember(ctx, req.(*BatchAddMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_InitMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).InitMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/InitMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).InitMember(ctx, req.(*InitMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).DeleteMember(ctx, req.(*DeleteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_SetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).SetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/SetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).SetMember(ctx, req.(*SetMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/UpdateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).UpdateMember(ctx, req.(*UpdateMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_UpdateSomeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSomeMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).UpdateSomeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/UpdateSomeMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).UpdateSomeMember(ctx, req.(*UpdateSomeMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_SortMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).SortMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/SortMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).SortMember(ctx, req.(*SortMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_ErrorTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).ErrorTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/ErrorTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).ErrorTest(ctx, req.(*GetMemberByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberRPC_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberRPCServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberRPC/AddFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberRPCServer).AddFavorite(ctx, req.(*AddFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MemberRPC",
	HandlerType: (*MemberRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMemberByID",
			Handler:    _MemberRPC_GetMemberByID_Handler,
		},
		{
			MethodName: "GetMemberByPhone",
			Handler:    _MemberRPC_GetMemberByPhone_Handler,
		},
		{
			MethodName: "GetMemberMaxAge",
			Handler:    _MemberRPC_GetMemberMaxAge_Handler,
		},
		{
			MethodName: "QueryMemberByName",
			Handler:    _MemberRPC_QueryMemberByName_Handler,
		},
		{
			MethodName: "QueryMemberByIDs",
			Handler:    _MemberRPC_QueryMemberByIDs_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _MemberRPC_AddMember_Handler,
		},
		{
			MethodName: "BatchAddMember",
			Handler:    _MemberRPC_BatchAddMember_Handler,
		},
		{
			MethodName: "InitMember",
			Handler:    _MemberRPC_InitMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _MemberRPC_DeleteMember_Handler,
		},
		{
			MethodName: "SetMember",
			Handler:    _MemberRPC_SetMember_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _MemberRPC_UpdateMember_Handler,
		},
		{
			MethodName: "UpdateSomeMember",
			Handler:    _MemberRPC_UpdateSomeMember_Handler,
		},
		{
			MethodName: "SortMember",
			Handler:    _MemberRPC_SortMember_Handler,
		},
		{
			MethodName: "ErrorTest",
			Handler:    _MemberRPC_ErrorTest_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _MemberRPC_AddFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}
