// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package main

import (
	"flag"
	"fmt"
	"github.com/davecgh/go-spew/spew"
	"go-zero-study/app/service/member/api"
	"go-zero-study/app/service/member/config"
	"go-zero-study/app/service/member/internal/server/rpc"
	"go-zero-study/app/service/member/internal/service"
	"go-zero-study/core/conf"
	"go-zero-study/core/logx"
	"go-zero-study/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "./app/service/member/cmd/member.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	spew.Dump(c)
	svc := service.New(c)
	srv := rpc.New(svc)

	s, err := zrpc.NewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		api.RegisterMemberRPCServer(grpcServer, srv)
	})
	logx.Must(err)

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
